name: Metrics
on:
    schedule: [{ cron: "0 0 * * *" }]
    workflow_dispatch:
    push: { branches: ["main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: Penguinlay/fork-lowlighter-metrics@latest
              with:
                  clean_workflows: all
                  config_animations: yes
                  config_base64: yes
                  config_display: regular
                  config_gemoji: yes
                  config_octicon: yes
                  config_order: achievements, base.header, introduction, base.activity+community, base.repositories, topics, habits, isocalendar, music, screenshot, fortune
                  config_output: svg
                  config_padding: 0, 8 + 2%
                  config_timezone: America/Los_Angeles
                  config_twemoji: yes
                  debug_flags: ""
                  debug_print: no
                  debug: no
                  delay: 0
                  dryrun: no
                  experimental_features: ""
                  filename: data/images/metrics.*
                  notice_releases: yes
                  plugins_errors_fatal: no
                  quota_required_graphql: 200
                  quota_required_rest: 200
                  quota_required_search: 0
                  retries_delay_output_action: 120
                  retries_delay: 300
                  retries_output_action: 5
                  retries: 3
                  template: classic
                  token: ${{ secrets.METRICS_TOKEN }}
                  use_mocked_data: no
                  use_prebuilt_image: yes
                  user: Penguinlay
                  verify: no

                  base: header, activity, community, repositories, metadata
                  base_hireable: no
                  base_indepth: yes
                  commits_authoring: Penguinlay, sheinlinphyo@gmail.com, sheinlinphyo@berkeley.edu
                  extras_css: |
                      h1.field, h2.field {
                          border-bottom: 1px solid #777;
                          color: #777;
                          font-weight: 900;
                          margin: 12px 0;
                          padding-bottom: 4px;
                      }
                      .items-wrapper > section:first-child > h2 {
                          display: none;
                      }
                      .achievements {
                          padding: 20px;
                      }
                      .achievement {
                          background-color: rgb(41, 44, 51);
                          border-radius: 5px;
                          border: 0.1px solid #fff;
                          margin: 0;
                          padding: 4px 10px;
                      }
                      .topics {
                          align-content: center;
                          align-items: center;
                          display: flex;
                          flex-flow: row wrap;
                          justify-content: center;
                      }
                      .tracklist-container {
                          align-content: normal;
                          align-items: center;
                          display: flex;
                          flex-flow: row nowrap;
                          justify-content: center;
                      }
                      .tracklist-container > .field {
                          color: #1DB954;
                      }
                  extras_js: |
                      document.getElementsByClassName("tracklist")[0].parentElement.classList.add("tracklist-container");
                  repositories_affiliations: ""
                  repositories_batch: 100
                  repositories_forks: no
                  repositories_skipped: ""
                  repositories: 200
                  users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com

                  plugin_achievements: yes
                  plugin_achievements_display: detailed
                  plugin_achievements_ignored: ""
                  plugin_achievements_limit: 0
                  plugin_achievements_secrets: yes
                  plugin_achievements_threshold: C

                  plugin_fortune: yes

                  plugin_habits: yes
                  plugin_habits_charts_type: chartist
                  plugin_habits_charts: no
                  plugin_habits_days: 30
                  plugin_habits_facts: yes
                  plugin_habits_from: 1000
                  plugin_habits_trim: no

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year

                  plugin_introduction: yes
                  plugin_introduction_title: yes

                  plugin_lines: yes
                  plugin_lines_skipped: ""

                  plugin_music: yes
                  plugin_music_limit: 5
                  plugin_music_mode: top
                  plugin_music_played_at: no
                  plugin_music_provider: spotify
                  plugin_music_time_range: short
                  plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
                  plugin_music_top_type: tracks
                  plugin_music_user: ${{ secrets.SPOTIFY_USERNAME }}

                  plugin_screenshot: yes
                  plugin_screenshot_background: yes
                  plugin_screenshot_selector: "#comic img"
                  plugin_screenshot_title: XKCD of the Day
                  plugin_screenshot_url: https://xkcd.com

                  plugin_topics: yes
                  plugin_topics_limit: 20
                  plugin_topics_mode: icons
                  plugin_topics_sort: stars

                  plugin_traffic: yes
                  plugin_traffic_skipped: ""
