name: Metrics
on:
    schedule: [{ cron: "0 0 * * *" }]
    workflow_dispatch:
    push: { branches: ["main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: Penguinlay/metrics@master
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: Penguinlay
                  template: classic
                  base: header, activity, community, repositories, metadata
                  config_timezone: America/Los_Angeles
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year
