name: Metrics
on:
    schedule: [{ cron: "0 0 * * *" }]
    workflow_dispatch:
    push: { branches: ["main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: Penguinlay/metrics@master
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: Penguinlay
                  filename: data/images/metrics.*
                  template: classic
                  config_timezone: America/Los_Angeles
                  config_twemoji: yes
                  config_gemoji: yes
                  config_octicon: yes
                  config_display: regular
                  config_animations: yes
                  config_base64: yes
                  config_padding: 0, 8 + 11%
                  config_output: svg
                  retries: 3
                  retries_delay: 300
                  retries_output_action: 5
                  retries_delay_output_action: 120
                  clean_workflows: all
                  delay: 0
                  quota_required_rest: 200
                  quota_required_graphql: 200
                  quota_required_search: 0
                  notice_releases: yes
                  use_prebuilt_image: yes
                  plugins_errors_fatal: no
                  debug: no
                  verify: no
                  debug_flags: ""
                  debug_print: no
                  dryrun: no
                  experimental_features: ""
                  use_mocked_data: no

                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  base_hireable: no
                  repositories: 200
                  repositories_batch: 100
                  repositories_forks: no
                  repositories_affiliations: ""
                  repositories_skipped: ""
                  users_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot], actions-user, action@github.com
                  commits_authoring: Penguinlay, sheinlinphyo@gmail.com, sheinlinphyo@berkeley.edu

                  plugin_achievements: yes
                  plugin_achievements_threhold: C
                  plugin_achievements_secrets: yes
                  plugin_achievements_display: compact
                  plugin_achievements_limit: 0
                  plugin_achievements_ignored: ""

                  plugin_fortune: yes

                  plugin_habits: yes
                  plugin_habits_from: 1000
                  plugin_habits_days: 30
                  plugin_habits_facts: yes
                  plugin_habits_charts: yes
                  plugin_habits_charts_type: chartist
                  plugin_habits_trim: no

                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year

                  plugin_introduction: yes
                  plugin_introduction_title: yes

                  plugin_lines: yes
                  plugin_lines_skipped: ""

                  plugin_music: yes
                  plugin_music_provider: spotify
                  plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
                  plugin_music_mode: top
                  plugin_music_limit: 5
                  plugin_music_played_at: no
                  plugin_music_time_range: short
                  plugin_music_top_type: tracks
                  plugin_music_user: ${{ secrets.SPOTIFY_USERNAME }}

                  plugin_pagespeed: yes
                  plugin_pagespeed_url: https://www.sheinlinphyo.com
                  plugin_pagespeed_detailed: yes

                  plugin_screenshot: yes
                  plugin_screenshot_title: XKCD of the Day
                  plugin_screenshot_url: https://xkcd.com
                  plugin_screenshot_selector: "#comic img"
                  plugin_screenshot_background: yes
                  plugin_pagespeed_screenshot: yes
                  plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

                  plugin_topics: yes
                  plugin_topics_mode: icons
                  plugin_topics_sort: stars
                  plugin_topics_limit: 20

                  plugin_traffic: yes
                  plugin_traffic_skipped: ""
